---

- name: create a stack, specify role that cloudformation assumes
  cloudformation:
    stack_name: "ansible-cloudformation"
      state: "present"
      region: "ap-southeast-1"
      disable_rollback: true
      validate_certs: false
      template: "../templates/ecs.json"
      template_parameters:
        image: "{{image}}"
        tag: "{{tag}}"

