---

- name: install docker
  shell: pip3 install docker

- name: "docker images clean up"
  docker_image:
    state: absent
    name: "{{image}}"

- name: kill old container
  docker_container:
    name: "{{app_name}}"
    state: absent

- name: pull image
  command: docker pull "{{image}}:{{tag}}"

- name: start new service container
  docker_container:
    name:  "{{app_name}}"
    image: "{{image}}:{{tag}}"
    restart_policy: always
    network_mode: bridge
    exposed_ports: "30001"
    published_ports: "30001:8001"

- name: Wait for server to pass health-checks
  health_check:
    url: "http://localhost:30001/order-service/orders/1234567890"
  register: result

- name: health check passed, record it
  template:
    src: last_success.txt.j2
    dest: "/tmp/{{app_name}}_last_success.txt"
  when: result.status == "healthy"

- include: rollback.yml
  when: result.status == "faulty"
