---
- name: if health check failed, roll back
  command: cat /tmp/{{app_name}}_last_success.txt
  register: last_success

- set_fact:
    last_success_tag: "{{last_success.stdout}}"

- name: remove failed container
  docker_container:
    name: "{{app_name}}"
    state: absent

- name: start new container with historical version
  docker_container:
    name:  "{{app_name}}"
    image: "{{image}}:{{tag}}"
    restart_policy: always
    network_mode: host

- fail:
    msg: "Deploy to {{tag}} failed, roll back to last success {{last_success_tag}}"
