#! /bin/bash

app_image=suyue466300750/order-service:${BUILD_NUMBER}

docker run --rm -u root -v /tmp/gradle-cache:/home/gradle/.gradle/caches -v $(pwd):/app -w /app gradle:4.7.0-jdk8 gradle build
docker build -f order-service/Dockerfile -t ${app_image} order-service
docker login docker.io -u suyue466300750 -p 200920008bama
docker push ${app_image}
docker rmi ${app_image}

docker network rm sales
docker network create sales
